### ISSUE TITLE
[Proposal] new VID that can be add to pid.codes

### ISSUE THREAD

**Issue by www2000** [pidcodes/pidcodes.github.com#375]
I bereave that the the following VID are candidates that are save to include in this project through mergers, bankruptcy, shutdown there operations, etc.
the VID with a star ( * ) on the end are most likely to be save to include in this project.
bankruptcy/shutdown or mergers that was more than 10 years at go.

0430  Sun Microsystems, Inc. 
045d  Nortel Networks, Ltd *
04a0  Digital Equipment Corp *
04ab  Chromatic Research *
051a  WYSE Technology
059b  Iomega Corp *
08b9  RadioShack Corp. (Tandy) *
0830  Palm, Inc. 
08c8  2Wire, Inc.
0b62  Orange Micro, Inc. *
0bc7  X10 Wireless Technology, Inc. 
0e22  Symbian Ltd.
12ef  Tapwave, Inc. *

**Comment by peternewman** [comment]
@www2000 from my understanding it's sadly a bit more involved than just finding companies who have gone bust. Firstly you'd need a list of every PID they ever issued, otherwise if you've got one of their genuine devices, and some open source hardware plugged in they could potentially clash.

Secondly, as per http://pid.codes/about/ the VID is genuinely owned by pid.codes, well as much as can be possible:

> We have been gifted a Vendor ID by a company that was issued one by USB-IF and has since ceased trading; they obtained the Vendor ID before the USB-IF changed their licensing terms to prohibit transfers or subassignments.

So your old companies may meet the second part, but unless they gave the VID to pid.codes, potentially other people could use it directly and you get the risk of VID/PID clash again.

**Comment by Arachnid** [comment]
Thank you for the suggestions - but as @peternewman points out, we need more clarity around the status of a VID before we can start assigning PIDs under it.
